### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by spisakt** [spisakt/BWAS_comment#2]
- [ ] update paper info in vido, page description, readme
- [x] update youtube video, fix aspect ratio
- [x] links to mlconfound and maybe other works
- [x] links to the labs
